flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 63cb8f83deb68f416ba95afe3d1c5372a40dca43
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: e636a3a7a34529116e91c1b1dda567701f1daa18
  subdirs:
  - reflex-dom-core
  - reflex-dom
  extra-dep: true

- location:
    git: https://github.com/hansroland/reflex-dom-brownies
    commit: d5cd8e67fd2153ab53505271d92a6c9b4c589ec8    
  extra-dep: true

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
        url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
        sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
extra-deps:
- ghcjs-dom-0.8.0.0
- ghcjs-dom-jsaddle-0.8.0.0
- jsaddle-0.8.3.2
- jsaddle-dom-0.8.0.0
- jsaddle-warp-0.8.3.1
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1
- ghcjs-dom-jsffi-0.8.0.0
- bytestring-strict-builder-0.4.5
- base-prelude-1.2.0.1
compiler-check: match-exact
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
resolver: lts-7.19









