flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 2fe0f566f8d6b6eceb178a85516643390111bb83
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: 706ab47df9729bdc5c4ac3f4d8dfd4661d9f6e1a
  subdirs:
  - reflex-dom
  - reflex-dom-core
  extra-dep: true

- location:
    git: https://github.com/hansroland/reflex-dom-brownies
    commit: 29a6ff785ebbdca910ccc2791d45c52ba2ef992b    
  extra-dep: true

# Use  dependent-sum-0.3.2.2 from github.
# Version on cabal has wrong base dependency
- location:
    git: https://github.com/mokus0/dependent-sum
    commit: 02173260ce60113ac442da04bf40139119271380 
  extra-dep: true
  
extra-deps:
- ghcjs-dom-0.8.0.0
- ghcjs-dom-jsaddle-0.8.0.0
- jsaddle-0.8.3.2
- jsaddle-dom-0.8.0.0
- jsaddle-webkit2gtk-0.8.3.1
- webkit2gtk3-javascriptcore-0.14.2.1
- gi-webkit2-4.0.12
- gi-javascriptcore-4.0.12
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1
- dependent-sum-template-0.0.0.5
resolver: lts-8.12
